### ISSUE TITLE
Implement get velocity from function coefficients

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/eal#36]

**Comment by kberryUSGS** [comment]
Are the function coefficients we pass in to this function coefficients for a velocity function, or are we passing the coefficients for a position function in to this function? I'm asking because if they are coefficients to a velocity function, does this basically do the same thing as the `getPosition` function?

**Comment by jessemapel** [comment]
They are position function coefficients, so we need to evaluate the derivative.

**Comment by kberryUSGS** [comment]
@jessemapel :+1 Thanks, I will go ahead and do this. That does make more sense -- I wasn't sure why / how the consumer of this library was likely to be able to provide coefficients for a velocity polynomial?

**Comment by jessemapel** [comment]
Done by #52
